name: Terraform Plan and Apply

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: List files (debugging)
        run: ls -la

      - name: List infra files (debugging)
        run: ls -la infra/

      - name: Terraform Init
        working-directory: infra
        run: |
          terraform init
          terraform validate

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -input=false
        

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve -input=false
        
